CREATE TABLE SCHOOL_SUBJECT (
	ID BIGINT,
	DIFFICULTY INT,
	NAME VARCHAR(32),
	DESCRIPTION VARCHAR(512)
);

CREATE TABLE SCHOOL_SUBJECT_TRANSLATION (
	SCHOOL_SUBJECT_ID BIGINT,
	LANGUAGE_ID VARCHAR2(16),
	NAME VARCHAR(32),
	DESCRIPTION VARCHAR(512)
);
